ATTOM/urls.py
from django.urls import path, include
from . import views

#
# If you want to make your own custom paths,
# the first parameter is the URL (such as example.com/**admin**),
# the second parameter is the function to call to produce the web page,
# the third is just a name for the path.
#

app_name = 'attom'
urlpatterns = [
  #home page
  path('', views.index, name='index'),

  path('property_detail/', views.property_detail, name='property_detail.html'),

  # Include default auth urls.
  path('', include('django.contrib.auth.urls')),

  # path for looking up property detail
  # this URL sends rquests to the view function get_property()
  path('property_lookup/', views.get_property, name='get_property'),



]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path("", include('realestate_app.urls')),
    path("attom/", include('attom.urls')),

]

realestate_app/urls.py
"""Defines URL patterns for realestate_app"""

# Import the path function needed when mapping URLs to views
from django.urls import path, include
# from django.conf.urls import url

# Import views model.  Dot tells Pyton to import from same dir
from . import views

app_name = 'realestate_app'


"""
1. The first argument is a string that helps Django route the current request properly.
Django receives the requested URL and tries to route the the request to a view.
It does this by searching all the URL patterns we've defined to find one that matches
the current request.
Django ignores the base URL for the project (http://localhost:8000/), so the empty string
matches the base URL.
2. The second arg in path() specifies which function to call in view.py
3. The third arg provides the name 'index' for this URL pattern so we can refer to it in other
code sections. We can provide this name rather than writing out the URL to refer to home page. """

urlpatterns = [

    # Home page
    # /realestate_app
    path('', views.index, name='index'),

    # PAGE THAT SHOWS ALL CONTRACTS
    # /realestate_app/contracts
    path('contracts/', views.contracts, name='contracts'),

    # PAGE THAT SHOWS ALL ACTIONS FOR ONE CONTRACT
    # /realestate_app/contract/<id>
    path('contracts/<int:contract_id>/', views.contract, name='contract'),

     # /realestate_app/contractlist
    path('contractlist/', views.contractlist, name='contractlist'),

    # /realestate_app/actions
    path('actions/', views.actions, name='actions'),

     # /realestate_app/new_contractaction
    path('new_contractaction/', views.new_action, name='new_contractaction'),

    # /realestate_app/actions/<id>
    path('actions/<int:contractAction_id>', views.action, name='action'),

    # /realestate_app/persons
    path('persons/', views.persons, name='persons'),

    # /realestate_app/persons/<id>
    path('persons/<int:person_id>', views.person, name='person'),

    ####################################
    # FORMS
    ####################################
    # Page for adding new contract
    # this URL pattern sends requests to the view function new_contract()
    path('new_contract/', views.new_contract, name='new_contract' ),

    # Page for adding new action
    path('new_action/<int:contract_id>/', views.new_action, name='new_action' ),

   # Page for further contrct detail
    path('contract_detail/', views.contract_detail, name='contract_detail'),


    ####################################
    # END OF FORMS
    ####################################

  # PAGE FOR EDITING AN ACTION
    path('edit_action/<int:action_id>/', views.edit_action, name='edit_action'),

  # About page
    path('about/', views.about, name='about'),



  # Page for finding address in ATTOM database
  # this URL sends requests to the view function
  # PROPERTY LOOKUP ON ATTOM DATABASE
    path('property_lookup/', views.property_lookup, name='property_lookup'),
    path('attom_location/', views.attom_location, name="attom_location"),

  # practice to create a URL to match a view
  path('first/', views.first, name='first')



]

users/urls.py
"""Defines URL patterns f9r users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register')
]

ATTOM/models.py
from django.db import models

# Create your models here.

ATTOM/forms.py
from django import forms


class AddressForm(forms.Form):
    address = forms.CharField(label="stree", max_length=100)
    address2 = forms.CharField(label="city state, zip", max_length=100)

#  COPY THIS:
class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

ATTOM/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
# from python file in same directory called prop_detail_func.py
# import one specific function: get_prop_detail()
from .prop_detail_func import get_prop_detail
from .forms import AddressForm

# Create your views here.
def index(request):
  return render(request, 'attom/index.html')

def property_detail(request):
  """ The Presentation of Property Data from ATTOM Database """
  # function goes out to public database and retries information and
  # puts in a list called "parsed_list"
  parsed_list = get_prop_detail()

  # Abstract specific fields from list
  context = {
    'property': parsed_list,
    'property_identifier': parsed_list[0]["identifier"]["attomId"],
    'property_address': parsed_list[0]["address"]["oneLine"],
    'property_lot_size': parsed_list[0]["lot"]["lotsize1"],
    'property_yearbuilt': parsed_list[0]["summary"]["yearbuilt"],
    'property_propertyType': parsed_list[0]["summary"]["propertyType"],
  }
  return render(request, 'attom/property_detail.html', context)


def get_property(request):
  """Form for getting address for ATTOM database search"""
  # if this is a POST request we need to process the form data
  if request.method != 'POST':
    # No data submitted; create a blank form.
    # create a form instance and populate it with data from the request:
    form = AddressForm()
    # check whether it is valid:
  else:
    # POST data submitted; process data.
    form = AddressForm(data=request.POST)
    if form.is_valid():
      form.save()
      return redirect("attom:property_detail.html")

  #Display a blank or invalid form.
  context = {'form': form}
  return render(request, "attom/property_detail.html",  context)

ATTOM/templates/attom/base.html
<!-- BASE HTML -->
{% load django_bootstrap5 %}
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Attom Database Search App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border ">

        <a class="navbar-brand" href=" {% url 'realestate_app:index' %} "> Attom Database Search App</a>

        <button class="navbar-toggler" type="button" data-toggle="collage"  data-target="navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'realestate_app:contracts'%}"> Search 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'realestate_app:new_contract'%}"> Search 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'realestate_app:persons'%}"> Search 3</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'realestate_app:property_lookup'%}"> Search 4</a>
            </li>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'realestate_app:about'%}"> Search 5</a>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item mt-2">
                    <span class="navbar-text">Hello,{{user.username  }} </span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'users:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'users:login' %}">Log in </a>
                </li>
            {% endif %}
        </ul>
    </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

ATTOM/templates/attom/index.html
{% extends "attom/base.html" %}
{% load static %}

<!-- DOCTYPE html -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Welcome Home {% endblock %}</title>
</head>

{% block page_header %}
  <div class="container text-center">
    <div class="row">
      <div class="column">
        <h6>Powered by:</h6>
      </div>
      <div class="column">
        <img src="{% static 'logo.png' %}" width="150" height="40">
      </div>
      <div class="column">
        <title>Database Search</title>
      </div>
      <div class="column">
        <div class="bg-secondary bg-gradient  text-white">
          <h6>Database Search</h6>
        </div>
      </div>
    </div>
  </div>




<body>
<nav aria-label="main navigation" class="navbar is-light" role="navigation">
    <div class="navbar-brand">
        <div class="navbar-item">

        </div>
    </div>
</nav>
</body>

{% endblock page_header %}

ATTOM/templates/attom/property_detail.html
{% extends "attom/base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Property Detail</title>
    <link crossorigin="anonymous"
          href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css"
          integrity="sha256-8B1OaG0zT7uYA572S2xOxWACq9NXYPQ+U5kHPV1bJN4="
          rel="stylesheet"/>
    <div class="column">
        <img src="{% static 'logo.png' %}" width="150" height="40">
        <h5>Search Results: </h5>
    </div>
</head>
<body>
<nav aria-label="main navigation" class="navbar is-light" role="navigation">
    <div class="navbar-brand">
        <div class="navbar-item">
            <img src="{% static 'logo.png' %}" width="100" height="40"
                 style="margin-right: 0.5em;">Search Results
        </div>
    </div>
</nav>

<table class="table is-fullwidth is-striped is-bordered">
    <thead>
    <tr>
        <th>Property Street Address</th>
        <th>Attom ID</th>
        <th>Lot Size in Acreage</th>
        <th>Year Built</th>
        <th>Property Type</th>
        <th>Field 6</th>
        <th>Field 7</th>
    </tr>
    </thead>
    <tbody>
    {% for each in property %}
    <tr>
        <th>{{ property_address }}</th>
        <td>{{ property_identifier }}</td>
        <td>{{ property_lot_size }}</td>
        <td>{{ property_yearbuilt}}</td>
        <td>{{ property_propertyType}}</td>
        <td>{{ property.1 }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

</body>
</html>
{% endblock content %}

ATTOM/templates/attom/property_lookup.html
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Enter property that you are searching for: </h2>
{% csrf_token %}
<form class="row g-3">
    <div class="col-12">
      <label for="inputAddress" class="form-label">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-12">
      <label for="inputAddress2" class="form-label">Address 2</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="City and 2 Letter State">
    </div>
    <div class="col-12">
      <button onclick="attom/property_detail" type="submit" class="btn btn-primary">Search</button>
    </div>
</form>
{% endblock page_header %}