ATTOM/urls.py
from django.urls import path, include
from . import views

#
# If you want to make your own custom paths,
# the first parameter is the URL (such as example.com/**admin**),
# the second parameter is the function to call to produce the web page,
# the third is just a name for the path.
#

app_name = 'attom'
urlpatterns = [
  #home page
  path('', views.index, name='index'),

  path('property_detail/', views.property_detail, name='property_detail.html'),

  # Include default auth urls.
  path('', include('django.contrib.auth.urls')),

  # path for looking up property detail
  # this URL sends rquests to the view function get_property()
  path('property_lookup/', views.get_property, name='get_property'),



]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path("", include('realestate_app.urls')),
    path("attom/", include('attom.urls')),

]

realestate_app/urls.py
"""Defines URL patterns for realestate_app"""

# Import the path function needed when mapping URLs to views
from django.urls import path, include
# from django.conf.urls import url

# Import views model.  Dot tells Pyton to import from same dir
from . import views

app_name = 'realestate_app'


"""
1. The first argument is a string that helps Django route the current request properly.
Django receives the requested URL and tries to route the the request to a view.
It does this by searching all the URL patterns we've defined to find one that matches
the current request.
Django ignores the base URL for the project (http://localhost:8000/), so the empty string
matches the base URL.
2. The second arg in path() specifies which function to call in view.py
3. The third arg provides the name 'index' for this URL pattern so we can refer to it in other
code sections. We can provide this name rather than writing out the URL to refer to home page. """

urlpatterns = [

    # Home page
    # /realestate_app
    path('', views.index, name='index'),

    # PAGE THAT SHOWS ALL CONTRACTS
    # /realestate_app/contracts
    path('contracts/', views.contracts, name='contracts'),

    # PAGE THAT SHOWS ALL ACTIONS FOR ONE CONTRACT
    # /realestate_app/contract/<id>
    path('contracts/<int:contract_id>/', views.contract, name='contract'),

     # /realestate_app/contractlist
    path('contractlist/', views.contractlist, name='contractlist'),

    # /realestate_app/actions
    path('actions/', views.actions, name='actions'),

     # /realestate_app/new_contractaction
    path('new_contractaction/', views.new_action, name='new_contractaction'),

    # /realestate_app/actions/<id>
    path('actions/<int:contractAction_id>', views.action, name='action'),

    # /realestate_app/persons
    path('persons/', views.persons, name='persons'),

    # /realestate_app/persons/<id>
    path('persons/<int:person_id>', views.person, name='person'),

    ####################################
    # FORMS
    ####################################
    # Page for adding new contract
    # this URL pattern sends requests to the view function new_contract()
    path('new_contract/', views.new_contract, name='new_contract' ),

    # Page for adding new action
    path('new_action/<int:contract_id>/', views.new_action, name='new_action' ),

   # Page for further contrct detail
    path('contract_detail/', views.contract_detail, name='contract_detail'),


    ####################################
    # END OF FORMS
    ####################################

  # PAGE FOR EDITING AN ACTION
    path('edit_action/<int:action_id>/', views.edit_action, name='edit_action'),

  # About page
    path('about/', views.about, name='about'),



  # Page for finding address in ATTOM database
  # this URL sends requests to the view function
  # PROPERTY LOOKUP ON ATTOM DATABASE
    path('property_lookup/', views.property_lookup, name='property_lookup'),
    path('attom_location/', views.attom_location, name="attom_location"),

  # practice to create a URL to match a view
  path('first/', views.first, name='first')



]

users/urls.py
"""Defines URL patterns f9r users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register')
]

realestate_app/forms.py
from django import forms
from .models import Contract, Action, ContractDetail, Person

from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class ContractForm(forms.ModelForm):
  class Meta:
    model = Contract
    fields = ['seller',
              'buyer',
              'listingAgent',
              'buyingAgent',
              'price',
              'address1',
              'address2',
              'city',
              'state',
              'zip',
              'contractDate',
              ]
    labels = {'text': ''}


class ContractDetailForm(forms.ModelForm):
  class Meta:
    model = ContractDetail
    fields = [
      'contractPDF',
      'mortgage',
      'mortgageAmount',
      'escrowAmount',
      'closedContract',
      'comments',
    ]
    labels = {'text': ''}


class ActionForm(forms.ModelForm):
  class Meta:
    model = Action
    fields = ['action',
              'actionPerson',
              'actionCompany',
              'actionNextStep',
              'actionFee',
              'actionDueDate',
              ]
    labels = {'text': ''}
    widgets = {'text': forms.Textarea(attrs={'cols': 80})}



  # class UserForm(UserCreationForm):

realestate_app/views.py
from django.shortcuts import render, redirect
from realestate_app.models import Action, Contract, Person, ContractDetail
from .models import Contract, Action, Person,  ContractDetail
from .forms import ContractForm, ActionForm
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.views.generic import TemplateView
from django.template import loader

import requests
import pprint

# Create your views here.
""" When a URL request matches the pattern we just defined, Django looks for a function
called index() in view.py.  Django then passes the request object to this view function.
 """


def index(request):
  """The home page for realestate_app """
  # Generate counts for some of the main objects
  num_contracts = Contract.objects.all().count()
  num_actions = Action.objects.all().count()
  num_persons = Person.objects.all().count()
  # num_my_actions = Action.objects.all().filter(owner=request.user).count()

  context = {
    'num_contracts': num_contracts,
    'num_actions': num_actions,
    'num_persons': num_persons,
    # 'num_my_actions' : num_my_actions,
  }

  return render(request, 'realestate_app/index.html', context=context)


@login_required
def contracts(request):
  """Show all contracts that are not closed
    closedYesNo == No
    """
  contracts = Contract.objects.filter(owner=request.user).order_by('addDate')
  context = {'contracts': contracts}
  return render(request, 'realestate_app/contracts.html', context)


@login_required
def contract(request, contract_id):
  """ Show a single contract and all its ACTIONS   """
  # Make sure the toic belongs to the current user.
  contract = Contract.objects.get(id=contract_id)
  if contract.owner != request.user:
    raise Http404

  actions = contract.action_set.order_by('action')

  context = {'contract': contract, 'actions': actions}

  return render(request, 'realestate_app/contract.html', context, )


def contractlist(request):
  """List all contracts"""
  contractlist = Contract.objects.order_by('AddDate')
  context = {'contractlist': contractlist}
  return render(request, 'realestate_app/contractlist.html', context)


def actions(request):
  """Show all actions"""
  actions = Action.objects.order_by('action')
  context = {'actions': actions}
  return render(request, 'realestate_app/actions.html', context)


@login_required
def action(request, contractaction_id):
  """Show details for one action """
  action = Action.objects.order_by('action')
  context = {'action': action}
  return render(request, 'realestate_app/action/int:<id>.html')


def persons(request):
  """Show all persons involved in one contract """
  action = Person.objects.order_by('last_name')
  context = {'persons': persons}
  return render(request, 'realestate_app/persons.html')


def person(request, person_id):
  """Show all information on one person """
  action = Person.objects.order_by('last_name')
  context = {'person': person}
  return render(request, 'realestate_app/persons/int<id>.html')


@login_required
def new_contract(request):
  """Add a new contract"""
  if request.method != 'POST':
    # No data submitted; create a blank form.
    form = ContractForm()
  else:
    # POST data submitted; process data.
    form = ContractForm(data=request.POST)
    if form.is_valid():
      new_contract = form.save(commit=False)
      new_contract.owner = request.user
      new_contract.save()
      return redirect('realestate_app:contracts')

  # Display a blank or invalid form.
  context = {'form': form}
  return render(request, 'realestate_app/new_contract.html', context)




@login_required
def new_action(request, contract_id):
  """Add a new action for a particular contract"""
  contract = Contract.objects.get(id=contract_id)

  if request.method != 'POST':
    # No data submitted, create a blank form.
    form = ActionForm()
  else:
    # POST data submitted, process data.
    form = ActionForm(data=request.POST)
    if form.is_valid():
      new_action = form.save(commit=False)
      new_action.contract = contract  # contract_action?
      new_action.save()
      return redirect('realestate_app:contract', contract_id=contract_id)

  # Display a blank or invalid form.
  context = {'contract': contract,
             'form': form
             }
  return render(request, 'realestate_app/new_action.html', context)


"""
1. When the edit_action page receive a GET request, the edit_action() function
returns a form for editing the entry.
2. When the pages receives a POST request with revised action text, it saves the
modified text into the database.
"""

#########################################################
@login_required
def edit_action(request, action_id):
  """ Edit an existing action . """
  action = Action.objects.get(id=action_id)
  contract = action.contract
  # if action.owner != request.user:ee
  # raise Http404

  if request.method != 'POST':
    # Initial request; pre-fill form with the current entry.
    form = ActionForm(instance=action)
  else:
    # POST data submitted; process data.
    form = ActionForm(instance=action, data=request.POST)
    if form.is_valid():
      form.save()
      return redirect('realestate_app:contract', contract_id=contract.id)

  context = {'action': action, 'contract': contract, 'form': form}
  return render(request, 'realestate_app/edit_action.html', context)



def about(request):
  # return HttpResponse('<h2> About Real Deal </h2>')
  return render(request, 'realestate_app/about.html')

def contract_detail(request):
  # return HttpResponse('<h2> About Real Deal </h2>')
  return render(request, 'realestate_app/contract_detail.html')

def property_lookup(request):
  # """ Hits ATTOM database for information"""
   return render(request, 'realestate_app/property_lookup.html')

def attom_location(request):
  # returns data from ATTOM DB
  baseUrl = 'https://api.gateway.attomdata.com'
  apiEndpoint = '/propertyapi/v1.0.0/property/detail'

  headers = {
    'apikey': "46d45307ab513b944f5fd8ea08b26a6a"
  }

  params = {
    "address1": "39678 Stephanie Drive",
    "address2": "Bethany Beach, DE"
  }

  # Send request, headers and params are both dicts
  response = requests.get(url=f'{baseUrl}{apiEndpoint}', headers=headers, params=params)

  # Parse full response, returning a dict
  jsonResponse = response.json()

  # print(f'response code: {response.status_code}\n\n')
  # print('Full Response:')
  # pprint.pprint(jsonResponse)
  # print('\n\n\n')

  # print(f'County: {jsonResponse["property"][0]["address"]["country"]}')
  # context = {'country' : "USA"}
  country1 = {jsonResponse["property"][0]["address"]["country"]}
  context = {'country': country1}
  return render(request,'realestate_app/attom_location.html', context)

def first(request):
  # template = loader.get_template('first.html')
  return render(request, 'realestate_app/first.html')
  # return HttpResponse(template.render())

realestate_app/templates/realestate_app/about.html
<!--   about.html  -->
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1>About "Real Deal" Application</h1>
{% endblock page_header %}

{% block content %}

  <h4>Real Deal was developed by Mark Brown to enhance the </h4>
  <h4>ability of realtors, real estate investors, and buyers </h4>
  <h4> and sellers of real estate to obtain more accurate and </h4>
  <h4>in depth pertinent information on real estate properties</h4>
  <h4>across the United States.</h4>

  <img src="../static/mbrown.jpeg" alt="Girl in a jacket" style="width:250px;height:300px;">

<div class="callout">
<h5><a href="{% url 'realestate_app:new_contract' %}"> Add a new contract</a></h5>
</div>
<p>Back to <a href="/">Home</a></p>
  {% endblock content %}

realestate_app/templates/realestate_app/actions.html
<!-- actions.HTML -->

{% extends "realestate_app/base.html" %}

{% block content %}

<p>ACTIONS</p>
<P>Here is a list of all actions for all contracts: </P>

<ul>
    {% for action in actions  %}
        <li>{{ action }}</li>
    {% empty %}
        <li> No actions have been added yet.</li>
    {% endfor %}

</ul>


<p>Back to <a href="/">Home</a></p>
<p>Remember:  The Real Deal helps you track and complete the actions to quickly close real estate deals. </p> 

{% endblock content %}

realestate_app/templates/realestate_app/attom_location.html
<!-- AttomLocation.html  -->
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h3>Attom Location Detail Information</h3>
{% endblock page_header %}

<body>
  {% block content %}
  <p>something should be below</p>
  <hr>
  <br>
  {{ country}}
  <hr>
  {% endblock content %}
</body>

realestate_app/templates/realestate_app/closings.html
{% extends "realestate_app/base.html" %}

<!--   Closings.html  -->

<head>
    {% block title %}<title>Closings</title>{% endblock %}
</head>
<body>
    {% block content %}
    <h1> Future Closings Page</h1>

    <p>Back to <a href="/">Home</a></p>
    {% endblock content %}
</body>

</html>

realestate_app/templates/realestate_app/contractlist.html
{% extends "realestate_app/base.html" %}

<!--   contractlist.html  -->

<head>
    {% block title %}<title>Contract List</title>{% endblock %}
</head>
<body>
    <!-- Django Tags perform programming logic inside brackets.  -->
    {% block content %}
  <h1> List of Contracts</h1>

  <ul>
    {% for each in contractlist %}
      <li>{{ each.propertyAddress }} - Sold by:  {{ each.seller }} to {{each.buyer }}</li>
    {% endfor %}
  </ul>


<!-- Next step -->
<ul>
{% for each in contractlist %}
  <h2>{{ each.propertyaddress }} {{ each.seller }}</h2>
  
  <p>Contract Date: {{ each.buyer}}</p>
  {% endfor %}
</ul>
  <p>Back to <a href="/">Home</a></p>
  

  {% endblock content %}
</body>

</html>

realestate_app/templates/realestate_app/contracts.html
<!--   Contracts.html  -->
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1>List of Real Estate Contracts</h1>
{% endblock page_header %}

{% block content %}

  <ul class=" bg-info p-2" style="--bs-bg-opacity: .15;" >
    {% for contract in contracts %}
      <ul><h5>
      <a  href="{% url 'realestate_app:contract' contract.id %}"> {{ contract }} </a>
    </h5></ul>
    {% empty %}
    <li> <h4>No contracts have been added yet.</h4></li>
    {% endfor %}
  </ul>
<!--
<div class="callout"> -->
<!--
<h5 background-color:indigo-100 ><a class="btn btn-outline-info" href="{% url 'realestate_app:new_contract' %}"> Add a new contract</a></h5>
</div>
<p>Back to <a class="btn btn-outline-dark" href="/">Home</a></p>
-->

<div class="btn-group" role="group" aria-label="Basic example">
  <a class="btn btn-outline-primary" href="{% url 'realestate_app:new_contract' %}">New Contract</a>
  <a class="btn btn-outline-success" href="/">Back to Home</a>
</div>


<!--
<p></p>
<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
  <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off">
  <label class="btn btn-outline-primary" for="btncheck1">Add New Contract</label>

  <input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off">
  <label class="btn btn-outline-primary" for="btncheck2">Back to Home</label>

</div>
-->
  {% endblock content %}

realestate_app/templates/realestate_app/edit_action.html
<!-- edit_action.html -->

{% extends "realestate_app/base.html"   %}
{% load django_bootstrap5 %}
<head>
    {% block title %}<title>Edit Action Form</title>{% endblock %}
</head>
<body>

  {% block content %}
  <h5>Edit Action Form</h5>


  <p><a class="btn btn-outline-success btn-sm" href="{% url 'realestate_app:contract' contract.id %}">{{contract}} </a></p>

  <p>Edit an action for a specific contract</p>

  <form class="form" action="{% url 'realestate_app:edit_action' action.id %}" method='post' >
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-success btn-sm" name="Submit">Save Action Changes</button>
  </form>

  <p>Back to <a class="btn btn-outline-success btn-sm" href="/">Home</a></p>
  {% endblock content %}


    <!--    -->


</body>

</html>

realestate_app/templates/realestate_app/first.html
<!DOCTYPE html>
<html>
<body>

<h1>Hellow World!</h1>
<h5>Welcome to my hidden page.  Look for more hidden pages to find information gems.</h5>

</body>
</html>

realestate_app/templates/realestate_app/index.html
<!-- INDEX.HTML -->

{% extends "realestate_app/base.html" %}

{% block page_header %}
    <div class="p-3 mb-2 bg-secondary bg-gradient  text-white">
        <h1 class="display-3">Track Your Real Estate Contracts</h1>

        <p class="lead">Input your own contracts, and keep a list of the actions needed to close the deal.  You can update contact and action information and set reminders.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 bg-success p-2" style="--bs-bg-opacity: .25;" >
                <p></p>
                <p class="lead">Number of Contracts in local Database: </strong>{{  num_contracts }} </p>
                <p class="lead">Number of Persons in local Database: </strong>{{ num_persons }}</p>
                <p class="lead">Number of My Actions:  </p>
                <p class="lead">My Actions Due Today:  {{ num_my_actions }}</p>
                <p class="lead">New Contracts in my area in Last 24 Hours:  </p>
                <p class="lead">Contracts Closed in my area in Last 24 Hours:  </p>
            </div>
            <div class="w-25 p-3" style="width: 120px; height: 120px ">  <!-- w-50 img-fluid   img-fluid col-md-6 -->
                <img src="../static/index-bg.jpeg" class="img-responsive" style="height:300px; ">
            </div>
        </div>
    </div>
    <br>    
    <div class="row"> 
        <div class="col-md-8 bg-success p-2" style="--bs-bg-opacity: .5;" > 2/3rds column</div>
        <div class="col-md-4 bg-success p-2" style="--bs-bg-opacity: .75;" > 2/3rds column</div>
    </div>    
    {% endblock page_header %}

realestate_app/templates/realestate_app/new_action.html
<!-- new_action.html -->
{% extends "realestate_app/base.html"   %}
{% load django_bootstrap5 %}

{% block page_header %}
    {% block title %}<h2>New Action Form</h2>{% endblock %}
    {% endblock page_header %}

  {% block content %}
  <p>Add new action:</p>

  <p><a href="{% url 'realestate_app:contract' contract.id %}">{{contract}} </a></p> 

  <p>Add a new contract action:</p>
  <form action="{% url 'realestate_app:new_action' contract.id %}" method='post' class="'form" >
    <!-- Prevents cross-site request forgery -->
    {% csrf_token %}
    {% bootstrap_form form %}
    {%  bootstrap_button button_type="submit" content="OK"  %}
  </form>

  <p>Back to <a href="/">Home</a></p>
  {% endblock content %}

realestate_app/templates/realestate_app/new_contract.html
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    {% block title %}<h2>New Contract Form</h2>{% endblock %}
{% endblock page_header %}

{% block content %}
  <form action="{% url 'realestate_app:new_contract' %}" method='post' class="form" >
    {% csrf_token %}
    {% bootstrap_form form %}
    {%  bootstrap_button button_type="submit" content="OK"  %}
  </form>

  
  <p>Back to <a href="/">Home</a></p>
  {% endblock content %}

realestate_app/templates/realestate_app/persons.html
<!-- PERSONS.HTML -->

{% extends "realestate_app/base.html" %}
{% load static %}

{% block content %}
<head>
    {% block title %}<title>List of Persons</title>{% endblock %}
</head>

    <h1>Person List</h1>
    {% if person_list %}
    <ul>
        {% for person in person_list %}
        <li>
            <p>{{ person.first_name }}   {{ person.last_name}}</p>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no people in the list.</p>
    {% endif %}

    <p>Back to <a href="/">Home</a></p>
{% endblock content %}

realestate_app/templates/realestate_app/property_lookup.html
{% extends "realestate_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Enter property that you are searching for: </h2>
{% csrf_token %}
<form class="row g-3">
    <div class="col-12">
      <label for="inputAddress" class="form-label">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-12">
      <label for="inputAddress2" class="form-label">Address 2</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="City and 2 Letter State">
    </div>
    <div class="col-12">
      <button onclick="    realestate_app/attom_location "    type="submit" class="btn btn-primary">Search</button>
    </div>
</form>
{% endblock page_header %}

realestate_app/templates/realestate_app/starter.html
{% extends "realestate_app/base.html" %}

<!--   STARTER PAGE.html  -->

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Title of Page</title>{% endblock %}
</head>
<body>
    {% block content %}
  <h1> Future Page</h1>
  {% endblock content %}
</body>

</html>